/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/rdu/Workspace/dronin/dRonin/flight/UAVCAN/pixcar/20501.CarCommand.uavcan
 */

#ifndef PIXCAR_CARCOMMAND_HPP_INCLUDED
#define PIXCAR_CARCOMMAND_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
# range [-1, 1]
float32 servo_cmd
float32 motor_cmd
******************************************************************************/

/********************* DSDL signature source definition ***********************
pixcar.CarCommand
saturated float32 servo_cmd
saturated float32 motor_cmd
******************************************************************************/

#undef servo_cmd
#undef motor_cmd

namespace pixcar
{

template <int _tmpl>
struct UAVCAN_EXPORT CarCommand_
{
    typedef const CarCommand_<_tmpl>& ParameterType;
    typedef CarCommand_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > servo_cmd;
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > motor_cmd;
    };

    enum
    {
        MinBitLen
            = FieldTypes::servo_cmd::MinBitLen
            + FieldTypes::motor_cmd::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::servo_cmd::MaxBitLen
            + FieldTypes::motor_cmd::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::servo_cmd >::Type servo_cmd;
    typename ::uavcan::StorageType< typename FieldTypes::motor_cmd >::Type motor_cmd;

    CarCommand_()
        : servo_cmd()
        , motor_cmd()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<64 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 20501 };

    static const char* getDataTypeFullName()
    {
        return "pixcar.CarCommand";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool CarCommand_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        servo_cmd == rhs.servo_cmd &&
        motor_cmd == rhs.motor_cmd;
}

template <int _tmpl>
bool CarCommand_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(servo_cmd, rhs.servo_cmd) &&
        ::uavcan::areClose(motor_cmd, rhs.motor_cmd);
}

template <int _tmpl>
int CarCommand_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::servo_cmd::encode(self.servo_cmd, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::motor_cmd::encode(self.motor_cmd, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int CarCommand_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::servo_cmd::decode(self.servo_cmd, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::motor_cmd::decode(self.motor_cmd, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature CarCommand_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xA4F78E0270BD5DDEULL);

    FieldTypes::servo_cmd::extendDataTypeSignature(signature);
    FieldTypes::motor_cmd::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef CarCommand_<0> CarCommand;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::pixcar::CarCommand > _uavcan_gdtr_registrator_CarCommand;

}

} // Namespace pixcar

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::pixcar::CarCommand >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::pixcar::CarCommand::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::pixcar::CarCommand >::stream(Stream& s, ::pixcar::CarCommand::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "servo_cmd: ";
    YamlStreamer< ::pixcar::CarCommand::FieldTypes::servo_cmd >::stream(s, obj.servo_cmd, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "motor_cmd: ";
    YamlStreamer< ::pixcar::CarCommand::FieldTypes::motor_cmd >::stream(s, obj.motor_cmd, level + 1);
}

}

namespace pixcar
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::pixcar::CarCommand::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::pixcar::CarCommand >::stream(s, obj, 0);
    return s;
}

} // Namespace pixcar

#endif // PIXCAR_CARCOMMAND_HPP_INCLUDED