/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/rdu/Workspace/dronin/dRonin/flight/UAVCAN/pixcar/25003.CarSpeed.uavcan
 */

#ifndef PIXCAR_CARSPEED_HPP_INCLUDED
#define PIXCAR_CARSPEED_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
# 4-byte float
float32 speed
******************************************************************************/

/********************* DSDL signature source definition ***********************
pixcar.CarSpeed
saturated float32 speed
******************************************************************************/

#undef speed

namespace pixcar
{

template <int _tmpl>
struct UAVCAN_EXPORT CarSpeed_
{
    typedef const CarSpeed_<_tmpl>& ParameterType;
    typedef CarSpeed_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 32, ::uavcan::CastModeSaturate > speed;
    };

    enum
    {
        MinBitLen
            = FieldTypes::speed::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::speed::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::speed >::Type speed;

    CarSpeed_()
        : speed()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<32 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    enum { DefaultDataTypeID = 25003 };

    static const char* getDataTypeFullName()
    {
        return "pixcar.CarSpeed";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool CarSpeed_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        speed == rhs.speed;
}

template <int _tmpl>
bool CarSpeed_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(speed, rhs.speed);
}

template <int _tmpl>
int CarSpeed_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::speed::encode(self.speed, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int CarSpeed_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::speed::decode(self.speed, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature CarSpeed_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0x5EF92FC5ABDE09A7ULL);

    FieldTypes::speed::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef CarSpeed_<0> CarSpeed;

namespace
{

const ::uavcan::DefaultDataTypeRegistrator< ::pixcar::CarSpeed > _uavcan_gdtr_registrator_CarSpeed;

}

} // Namespace pixcar

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::pixcar::CarSpeed >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::pixcar::CarSpeed::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::pixcar::CarSpeed >::stream(Stream& s, ::pixcar::CarSpeed::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "speed: ";
    YamlStreamer< ::pixcar::CarSpeed::FieldTypes::speed >::stream(s, obj.speed, level + 1);
}

}

namespace pixcar
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::pixcar::CarSpeed::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::pixcar::CarSpeed >::stream(s, obj, 0);
    return s;
}

} // Namespace pixcar

#endif // PIXCAR_CARSPEED_HPP_INCLUDED